// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-WhzSrqoTkWEaMLWxWBQvmOPIhON_6U',
    appId: '1:162266611818:web:65463fc39036c919488a13',
    messagingSenderId: '162266611818',
    projectId: 'flutter-bfce3',
    authDomain: 'flutter-bfce3.firebaseapp.com',
    storageBucket: 'flutter-bfce3.appspot.com',
    measurementId: 'G-714HCSMSVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnTmw_WC3GBJxM3qirHaua2jhI8MT-dk',
    appId: '1:162266611818:android:f9485b744a2f2b6c488a13',
    messagingSenderId: '162266611818',
    projectId: 'flutter-bfce3',
    storageBucket: 'flutter-bfce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJYUVWs-1h-Kiow0wEVDWkznaqWEHJW4',
    appId: '1:162266611818:ios:5574814127407447488a13',
    messagingSenderId: '162266611818',
    projectId: 'flutter-bfce3',
    storageBucket: 'flutter-bfce3.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJYUVWs-1h-Kiow0wEVDWkznaqWEHJW4',
    appId: '1:162266611818:ios:5574814127407447488a13',
    messagingSenderId: '162266611818',
    projectId: 'flutter-bfce3',
    storageBucket: 'flutter-bfce3.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa-WhzSrqoTkWEaMLWxWBQvmOPIhON_6U',
    appId: '1:162266611818:web:ac9e01062d90ae1c488a13',
    messagingSenderId: '162266611818',
    projectId: 'flutter-bfce3',
    authDomain: 'flutter-bfce3.firebaseapp.com',
    storageBucket: 'flutter-bfce3.appspot.com',
    measurementId: 'G-QM568RCNPN',
  );
}
